
name: Build project
on:
  pull_request:
  merge_group:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Test
        run: echo testing!
